services:
  - type: web
    name: sinic-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false          # se ingresa manual en el dashboard
      - key: ALLOWED_ORIGINS
        value: https://juan19-thor.github.io
      - key: DEBUG
        value: "false"
    plan: free
